# Generated by Django 3.2.9 on 2021-12-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0004_auto_20211208_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='password1',
            field=models.CharField(default='12345', max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='password2',
            field=models.CharField(default='12345', max_length=20),
        ),
    ]
