# Generated by Django 3.2.9 on 2021-12-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0006_auto_20211208_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={},
        ),
        migrations.AlterModelManagers(
            name='passenger',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_superuser',
        ),
    ]
